devices:
({
  type = "rtlsdr";
  index = 0;
  gain = 31.0;
  mode = "scan";
  channels:
  ({
    freqs = ( 122800000, 122700000, 133550000, 134600000, 132125000, 123450000, 122900000, 292200000, 379100000, 127575000, 133400000, 128975000, 131050000, 136875000 );
    labels = ( "Baraga/Local", "Houghton CTAF", "ZMP West UP", "ZMP High Alt", "Winnipeg Center", "Plane-to-Plane", "MULTICOM / SAR", "Duluth F-16s", "AR-217 Refuel", "Toronto 1", "Toronto 2", "Porter airlines", "Porter airlines", "Porter airlines" );
    squelch_snr_threshold = 18.0;
    outputs: (
      { type = "pulse"; },
      {
        type = "file";
        directory = "/home/eddie/airscan_hybrid/recordings";
        filename_template = "airband_activity";
      }
    );
  });
});
